server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: safecity_user
    password: safecity_password
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
        use_sql_comments: true

jwt:
  secret: safecitySecretKeyForJWTTokenGeneration2024
  expiration: 86400000 # 24 hours in milliseconds

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  show-actuator: false

logging:
  level:
    com.safecity: DEBUG
    org.springframework.security: DEBUG

