server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/safecity
    username: safecity_user
    password: safecity_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: safecitySecretKeyForJWTTokenGeneration2024
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.safecity: DEBUG
    org.springframework.security: DEBUG

